/*
 * Proyecto: xaWeb framework
 * Fichero: ZStyle.prg
 * Descripción: Style helper class
 * Autor: Ignacio Ortiz de Zuniga
 * Copyright 2025 OZ Software (marca comercial de Ortiz de Zúñiga SL)
 * Copyright 2025 Ortiz de Zúñiga SL
 * Important: VALUES clause is necessary in order to assing style to controls
 * Note: This classs automatically sets the styles of its parent control when its
         data is assigned. Be aware, that the value returned for this data
         members may not be accurate, since the style may be also changed on its
         parent directly
 */

#include "xaWeb.ch"

CLASS ZStyle FROM WBasicStyle
PUBLISHED:
   DATA Accent_color   VALUES "*"
   DATA Align_content  VALUES "stretch", "center", "flex-start", "flex-end", "space-between", "space-around", "space-evenly", "initial", "inherit"
   DATA Align_items    VALUES "normal", "stretch", "center", "flex-start", "flex-end", "start", "end", "baseline", "initial", "inherit"
   DATA Align_self     VALUES "normal", "stretch", "center", "flex-start", "flex-end", "baseline", "initial", "inherit"
   DATA All            VALUES "initial", "inherit", "unset"
   DATA Animation      VALUES "animation-name", "animation-duration", "animation-timing-function", "animatrion-delay", "animation-iteration-count", "animation-direction", "animation-fill-mode", "animation-play-state", "initial", "inherit"
   DATA Animation_delay VALUES "*"
   DATA Animation_direction VALUES "normal", "reverse", "alternate", "alternate-reverse", "initial", "inherit"
   DATA Animation_duration VALUES "*"
   DATA Animation_fill_mode VALUES "none", "forwards", "backwards", "bouth", "initial", "inherit"
   DATA Animation_iteration_count VALUES "*"
   DATA Animation_name VALUES "*"
   DATA Animation_play_state VALUES "paused", "running", "initial", "inherit"
   DATA Animation_timing_function  VALUES "linear", "ease", "ease-in", "ease-out", "step-start", "step-end", "steps", "cubic-bezier", "initial", "inherit"

   DATA Background VALUES "*"
   DATA Background_attachment VALUES "*"
   DATA Background_blend_mode VALUES "normal", "multiply", "screen", "overlay", "darken", "lighten", "color-dodge", "saturation", "color", "luminosity"
   DATA Background_clip  VALUES "border-box", "padding-box", "content-box", "initial", "inherit"
   DATA Background_color VALUES "*"
   DATA Background_image VALUES "*"
   DATA Background_origin VALUES "*"
   DATA Background_position VALUES "*"
   DATA Background_repeat VALUES "repeat", "repeat-x", "repeat-y", "space", "round", "initial", "inherit"
   DATA Background_size   VALUES "auto", "length", "percentage", "cover", "contain", "initial", "inherit"
   DATA Border VALUES "*"
   DATA Border_bottom VALUES "*"
   DATA Border_bottom_color VALUES "*"
   DATA Border_bottom_left_radius VALUES "*"
   DATA Border_bottom_right_radius VALUES "*"
   DATA Border_bottom_style VALUES "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset", "initial", "inherit"
   DATA Border_bottom_width VALUES "*"
   DATA Border_collapse VALUES "*"
   DATA Border_color VALUES "*"
   DATA Border_image VALUES "*"
   DATA Border_image_outset VALUES "*"
   DATA Border_image_repeat VALUES "*"
   DATA Border_image_slice VALUES "*"
   DATA Border_image_source VALUES "*"
   DATA Border_image_width VALUES "*"
   DATA Border_left VALUES "*"
   DATA Border_left_color VALUES "*"
   DATA Border_left_style VALUES "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset", "initial", "inherit"
   DATA Border_left_width VALUES "*"
   DATA Border_radius VALUES "*"
   DATA Border_right VALUES "*"
   DATA Border_right_color VALUES "*"
   DATA Border_right_style VALUES "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset", "initial", "inherit"
   DATA Border_right_width VALUES "*"
   DATA Border_spacing VALUES "*"
   DATA Border_style VALUES "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset", "initial", "inherit"
   DATA Border_top VALUES "*"
   DATA Border_top_color VALUES "*"
   DATA Border_top_left_radius VALUES "*"
   DATA Border_top_right_radius VALUES "*"
   DATA Border_top_style VALUES "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset", "initial", "inherit"
   DATA Border_top_width VALUES "*"
   DATA Border_width VALUES "*"
   DATA Bottom VALUES "*"
   DATA Box_decoration_break VALUES "slice", "clone", "initial", "inherit"
   DATA Box_reflect VALUES "none", "below", "above", "left", "right", "initial", "inherit", "*"
   DATA Box_shadow VALUES "*"
   DATA Box_sizing VALUES "content-box", "border-box", "initial", "inherit"
   DATA Break_after VALUES "auto", "all", "always", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "recto", "region", "right", "verso", "initial", "inherit"
   DATA Break_before VALUES "auto", "all", "always", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "recto", "region", "right", "verso", "initial", "inherit"
   DATA Break_inside VALUES "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "initial", "inherit"

   DATA Caption_side VALUES "top", "bottom", "initial", "inherit"
   DATA Caret_color VALUES "auto", "color", "initial", "inherit"
//   DATA Charset VALUES "*"
   DATA Clear VALUES "none", "left", "right", "both", "initial", "inherit"
   DATA Clip VALUES "auto", "shape", "initial", "inherit"
   DATA Color VALUES "*"
   DATA Color_Scheme VALUES "normal", "light", "dark", "only"
   DATA Column_count VALUES "*"
   DATA Column_fill VALUES "balance", "auto", "initial", "inherit"
   DATA Column_gap VALUES "*"
   DATA Column_rule VALUES "*"
   DATA Column_rule_color VALUES "*"
   DATA Column_rule_style VALUES "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset", "initial", "inherit"
   DATA Column_rule_width VALUES "*"
   DATA Column_span VALUES "none", "all", "initial", "inherit"
   DATA Column_width VALUES "*"
   DATA Columns VALUES "*"
   DATA Content VALUES "*"
   DATA Counter_increment VALUES "*"
   DATA Counter_reset VALUES "*"
   DATA Cursor VALUES "alias", "all-scroll", "auto" ,"cell", "col-resize", "context-menu", "copy", "crosshair", "default", "e-resize", "ew-resize", "grab", "grabbing", "help", "move", "n-resize", "ne-resize", "nesw-resize", "ns-resize", "nw-resize", "nwse-resize", "no-drop", "none", "not-allowed", "pointer", "progress", "row-resize", "s-resize", "se-resize", "sw-resize", "text", "url", "vertical-text", "w-resize", "wait", "zoom-in", "zoom-out", "initial", "inherit"

   DATA Direction VALUES "ltr", "rtl", "initial", "inherit"
   DATA Display VALUES "inline", "block", "contents", "flex", "grid", "inline-block", "inline-flex", "inline-grid", "inline-table", "list-item", "run-in", "table", "table-caption", "table-column-group", "table-header-group", "table-footer-group", "table-row-group", "table-cell", "table-column", "table-row", "none", "initial", "inherit"

   DATA Empty_cells VALUES "show", "hide", "initial", "inherit"

   DATA Filter VALUES "*"
   DATA Flex VALUES "*"
   DATA Flex_basis VALUES "*"
   DATA Flex_direction VALUES "row", "row-reverse", "column", "column-reverse", "initial", "inherit"
   DATA Flex_flow VALUES "*"
   DATA Flex_grow VALUES "*"
   DATA Flex_shrink VALUES "*"
   DATA Flex_wrap VALUES "nowrap", "wrap", "wrap-reverse", "initial", "inherit"
   DATA Float VALUES "none", "left", "right", "initial", "inherit"
   DATA Font VALUES "*"
   DATA Font_face VALUES "*"
   DATA Font_family VALUES "*"
   DATA Font_feature_settings VALUES "*"
   DATA Font_kerning VALUES "*"
   DATA Font_language_override VALUES "*"
   DATA Font_size VALUES "*"
   DATA Font_size_adjust VALUES "*"
   DATA Font_stretch VALUES "ultra-condensed", "extra-condensed", "condensed", "|semi-condensed", "normal", "semi-expanded", "expanded", "extra-expanded", "ultra-expanded", "initial", "inherit"
   DATA Font_style VALUES "normal", "italic", "oblique", "initial", "inherit"
   DATA Font_variant VALUES "normal", "small-caps", "initial", "inherit"
   DATA Font_variant_caps VALUES "normal", "small-caps", "all-small-caps", "petite-caps", "all-petite-caps", "unicase", "titling-caps", "initial", "inherit", "unset"
   DATA Font_weight VALUES "*"

   DATA Gap VALUES "*"
   DATA Grid VALUES "*"
   DATA Grid_area VALUES "*"
   DATA Grid_auto_columns VALUES "auto", "max-content", "min-content", "length;"
   DATA Grid_auto_flow VALUES "row", "column", "dense", "row dense", "column dense"
   DATA Grid_auto_rows VALUES "auto", "max-content", "min-content", "length"
   DATA Grid_column VALUES "*"
   DATA Grid_column_end VALUES "*"
   DATA Grid_column_start VALUES "*"
   DATA Grid_row VALUES "*"
   DATA Grid_row_end VALUES "*"
   DATA Grid_row_start VALUES "*"
   DATA Grid_template VALUES "*"
   DATA Grid_template_areas VALUES "*"
   DATA Grid_template_columns VALUES "*"
   DATA Grid_template_rows VALUES "*"

   DATA Hanging_punctuation VALUES "none", "first", "last", "allow-end", "force-end", "initial", "inherit"
   DATA Height VALUES "*"
   DATA Hyphens VALUES "none", "manual", "auto", "initial", "inherit"

   DATA Image_rendering VALUES "auto", "smooth", "high-quality", "crisp-edges", "pixelated", "initial", "inherit"
   DATA Import VALUES "*"
   DATA Isolation VALUES "auto", "isolate", "initial", "inherit"

   DATA Justify_content VALUES "flex-start", "flex-end", "center", "space-between", "space-around", "space-evenly", "initial", "inherit"

   DATA Justify_items VALUES "legacy","normal","stretch","positional alignment","overflow-alignment","baseline alignment","initial","inherit"
   DATA Left VALUES "*"
   DATA Letter_spacing VALUES "*"
   DATA Line_break VALUES "*"
   DATA Line_height VALUES "*"
   DATA List_style VALUES "*"
   DATA List_style_image VALUES "*"
   DATA List_style_position VALUES "inside","outside","initial","inherit"
   DATA List_style_type VALUES "disc", "armenian", "circle", "cjk-ideographic", "decimal", "decimal-leading-zero", "georgian", "hebrew", "hiragana", "hiragana-iroha", "ktakana", "katakana-iroha", "lower-alpha", "lower-greek", "lower-latin", "lower-roman", "none", "square", "upper-alpha", "upper-greek", "upper-latin", "upper-roman", "initial", "inherit"
   DATA Margin VALUES "*"
   DATA Margin_bottom VALUES "*"
   DATA Margin_left VALUES "*"
   DATA Margin_right VALUES "*"
   DATA Margin_top VALUES "*"
   DATA Max_height VALUES "*"
   DATA Max_width VALUES "*"
   DATA Min_height VALUES "*"
   DATA Min_width VALUES "*"
   DATA Mix_blend_mode VALUES "*"
   DATA Object_fit VALUES "fill","contain","cover","scale-down","none","initial","inherit"
   DATA Object_position VALUES "*"
   DATA Opacity VALUES "*"
   DATA Order VALUES "*"
   DATA Orphans VALUES "*"
   DATA Outline VALUES "*"
   DATA Outline_color VALUES "*"
   DATA Outline_offset VALUES "*"
   DATA Outline_style VALUES "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset", "initial", "inherit"
   DATA Outline_width VALUES "medium","thin","thick","length","initial","inherit"
   DATA Overflow VALUES "visible","hidden","clip","scroll","auto","initial","inherit"
   DATA Overflow_wrap VALUES "normal","anywhere","break-word","initial","inherit"
   DATA Overflow_x VALUES "visible","hidden","scroll","auto","initial","inherit"
   DATA Overflow_y VALUES "visible","hidden","scroll","auto","initial","inherit"

   DATA Padding VALUES "*"
   DATA Padding_bottom VALUES "*"
   DATA Padding_left VALUES "*"
   DATA Padding_right VALUES "*"
   DATA Padding_top VALUES "*"
   DATA Page_break_after VALUES "auto","always","avoid","left","right","initial","inherit"
   DATA Page_break_before VALUES "auto","always","avoid","left","right","initial","inherit"
   DATA Page_break_inside VALUES "auto","avoid","initial","inherit"
   DATA Perspective VALUES "*"
   DATA Perspective_origin VALUES "*"
   DATA Place_items VALUES "normal","legacy","value","initial","inherit"
   DATA Pointer_events VALUES "auto", "none", "initial","inherit"
   DATA Position VALUES "static","absolute","fixed","relative","sticky","initial","inherit"
   DATA Quotes VALUES "*"
   DATA Resize VALUES "none","both","horizontal","vertical","initial","inherit"
   DATA Right VALUES "*"

   DATA Scroll_behavior VALUES "auto","smooth","initial","inherit"
   DATA Tab_size VALUES "*"
   DATA Table_layout VALUES "auto","fixed","initial","inherit"
   DATA Text_align VALUES "left","right","center","justify","initial","inherit"
   DATA Text_align_last VALUES "auto","left","right","center","justify","start","end","initial","inherit"
   DATA Text_decoration VALUES "*"
   DATA Text_decoration_color VALUES "*"
   DATA Text_decoration_line VALUES "none","underline","overline","line-through","initial","inherit"
   DATA Text_decoration_style VALUES "solid","double","dotted","dashed","wavy","initial","inherit"
   DATA Text_emphasis VALUES "none","filled","open","dot","circle","double-circle","triangle","sesame","string","color","initial","inherit"
   DATA Text_indent VALUES "*"
   DATA Text_justify VALUES "auto","inter-word","inter-character","none","initial","inherit"
   DATA Text_orientation VALUES "mixed","upright","sideways","sideways-right","use-glyph-orientation","initial","inherit"
   DATA Text_overflow VALUES "clip","ellipsis","string","initial","inherit"
   DATA Text_shadow VALUES "*"
   DATA Text_transform VALUES "none","capitalize","uppercase","lowercase","initial","inherit"
   DATA Text_underline_position VALUES "auto","under","from-font","left","right","initial","inherit"
   DATA Top VALUES "*"
   DATA Transform VALUES "*"
   DATA Transform_origin VALUES "*"
   DATA Transform_style VALUES "flat","preserve-3d","initial","inherit"
   DATA Transition VALUES "*"
   DATA Transition_delay VALUES "*"
   DATA Transition_duration VALUES "*"
   DATA Transition_DATA VALUES "*"
   DATA Transition_timing_function VALUES "*", "linear","ease","ease-in","ease-out","ease-in-out","step-start","step-end","steps(int,start","end)","cubic-bezier(n,n,n,n)","initial","inherit"
   DATA Unicode_bidi VALUES "normal","embed","bidi-override","initial","inherit"
   DATA User_select VALUES "auto","none","text","all"
   DATA Vertical_align VALUES "baseline","length","sub","super","top","text-top","middle","bottom","text-bottom","initial","inherit"
   DATA Visibility VALUES "visible","hidden","collapse","initial","inherit"
   DATA White_space VALUES "normal","nowrap","pre","pre-line","pre-wrap","initial","inherit"
   DATA Widows VALUES "*"
   DATA Width VALUES "*"
   DATA Word_break VALUES "normal","break-all","keep-all","break-word","initial","inherit"
   DATA Word_spacing VALUES "*"
   DATA Word_wrap VALUES "normal","break-word","initial","inherit"
   DATA Writing_mode VALUES "horizontal-tb","vertical-rl","vertical-lr"
   DATA Z_index VALUES "*"
END CLASS

//------------------------------------------------------------------------------

